name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  greet-all:
    name: Greet All
    uses: n-hebert/learning-github-actions/.github/workflows/reusable.yml@main
    with:
      greet-name-matrix: '[ \"alice\", \"bob\", \"charlie\" ]'
