name: CI

on:
  push:
    branches: [ basic ]
  pull_request:
    branches: [ basic ]

  workflow_dispatch:

jobs:
  greet-all:
    name: Greet All
    uses: n-hebert/learning-github-actions/.github/workflows/reusable.yml@main
    with:
      greet-name-matrix: '[ "alice", "bob", "charlie" ]'
    secrets:
      ALICE: ${{ secrets.ALICE }}
      BOB: ${{ secrets.BOB }}
