name: Complex CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  greet-all:
    name: Greet All
    uses: n-hebert/testing-reusable-workflows/.github/workflows/reusable-complex-matrix.yml@main
    with:
      greeting-matrix: '[{greeting:"hello",greet_name:"alice"},{greeting:"bonjour",greet_name:"bob"},{greeting:"hola",greet_name:"charlie"}]'
