name: Complex CI

on:
  push:
    branches:
      -  main

  workflow_dispatch:
    inputs:
      run_list:
        description: "Which people to greet"
        type: string
        required: false
        default: ""

jobs:
  greet-all:
    name: Greet All
    uses: n-hebert/testing-reusable-workflows/.github/workflows/reusable-complex-matrix.yml@main
    with:
      greeting_matrix: |
        [
          { "greeting" : "hello", "greet_name" : "alice" },
          { "greeting" : "bonjour", "greet_name" : "bob" },
          { "greeting" : "hola", "greet_name" : "charlie" }
        ]

  # This will crash
  #greet-none:
  #  name: Greet None
  #  uses: n-hebert/testing-reusable-workflows/.github/workflows/reusable-complex-matrix.yml@main
  #  with:
  #    greeting_matrix: "[ ]"
