name: Reusable Complex Matrix Workflow
on: 
  workflow_call:
    inputs:
      greeting_matrix:
        description: "The matrix of greetings"
        required: true
        type: string
      run_list:
        description: "The greetings to run"
        required: false
        type: string
    secrets:
      conditional:
        description: "A value triggers the execution of a job"
        required: false

jobs:
  echo-inner-arg:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.run_list }}"

  greet-user:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          ${{ fromJson(inputs.greeting_matrix) }}
    # WARNING: This controls the whole matrix job, not the individual matrix members
    if: contains(inputs.run_list, 'bob') # This does not filter to just the "bob" job
    steps:
      - run: echo "${{ matrix.greeting }} ${{ matrix.greet_name }}"

  run-if-secret-sent:
    runs-on: ubuntu-latest
    if: secrets.conditional != null
    steps:
      - run: echo "Executing!"
