name: reusable-complex-matrix-workflow
on: 
  workflow_call:
    inputs:
      greeting-matrix:
        description: "The matrix of greetings"
        required: true
        type: string

jobs:
  greet-user:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ${{ fromJson(inputs.greeting-matrix) }}
    steps:
      - run: echo "${{ matrix.greeting }} ${{ matrix.greet-name }}"

