name: Reusable Complex Matrix Workflow
on: 
  workflow_call:
    inputs:
      greeting_matrix:
        description: "The matrix of greetings"
        required: true
        type: string
      run_list:
        description: "The greetings to run"
        required: false
        type: string

jobs:
  echo-inner-arg:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.run_list }}"

  greet-user:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          ${{ fromJson(inputs.greeting_matrix) }}
    # WARNING: This controls the whole matrix job, not the individual matrix members
    if: contains(inputs.run_list, 'bob')
    steps:
      - run: echo "${{ matrix.greeting }} ${{ matrix.greet_name }}"
