name: reusable-complex-matrix-workflow
on: 
  workflow_call:
    inputs:
      greeting_matrix:
        description: "The matrix of greetings"
        required: true
        type: string

jobs:
  greet-user:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          ${{ fromJson(inputs.greeting_matrix) }}
    if: ${{ github.events.input.run_list }} == null
    steps:
      - run: echo "${{ matrix.greeting }} ${{ matrix.greet_name }}"

