name: Reusable Complex Matrix Workflow
on: 
  workflow_call:
    inputs:
      greeting_matrix:
        description: "The matrix of greetings"
        required: true
        type: string
      run_list:
        description: "The greetings to run"
        required: false
        type: string

jobs:
  greet-user:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          ${{ fromJson(inputs.greeting_matrix) }}
    if: 'inputs.run_list == "" || contains(inputs.run_list, matrix.greet_name)'
    steps:
      - run: echo "${{ matrix.greeting }} ${{ matrix.greet_name }}"
